"""add_officer_overrides_table

Revision ID: 0d0d7eca3acb
Revises: 234e28a6f813
Create Date: 2025-12-30 21:31:08.628216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d0d7eca3acb'
down_revision: Union[str, None] = '234e28a6f813'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'officer_overrides',
        sa.Column('override_id', sa.Integer(), nullable=False),
        sa.Column('run_id', sa.Integer(), nullable=True),
        sa.Column('validation_result_id', sa.Integer(), nullable=True),
        sa.Column('validation_check_id', sa.Integer(), nullable=True),
        sa.Column('original_status', sa.String(length=20), nullable=False),
        sa.Column('override_status', sa.String(length=20), nullable=False),
        sa.Column('notes', sa.Text(), nullable=False),
        sa.Column('officer_id', sa.String(length=100), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
        sa.ForeignKeyConstraint(['validation_result_id'], ['validation_results.id'], ),
        sa.ForeignKeyConstraint(['validation_check_id'], ['validation_checks.id'], ),
        sa.PrimaryKeyConstraint('override_id')
    )
    op.create_index(op.f('ix_officer_overrides_run_id'), 'officer_overrides', ['run_id'], unique=False)
    op.create_index(op.f('ix_officer_overrides_validation_result_id'), 'officer_overrides', ['validation_result_id'], unique=False)
    op.create_index(op.f('ix_officer_overrides_validation_check_id'), 'officer_overrides', ['validation_check_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_officer_overrides_validation_check_id'), table_name='officer_overrides')
    op.drop_index(op.f('ix_officer_overrides_validation_result_id'), table_name='officer_overrides')
    op.drop_index(op.f('ix_officer_overrides_run_id'), table_name='officer_overrides')
    op.drop_table('officer_overrides')
    # ### end Alembic commands ###
