"""add_field_resolutions_table

Revision ID: d0d81345f976
Revises: 0d0d7eca3acb
Create Date: 2025-12-30 21:40:01.217398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0d81345f976'
down_revision: Union[str, None] = '0d0d7eca3acb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'field_resolutions',
        sa.Column('resolution_id', sa.Integer(), nullable=False),
        sa.Column('submission_id', sa.Integer(), nullable=False),
        sa.Column('field_key', sa.String(length=100), nullable=False),
        sa.Column('chosen_extracted_field_id', sa.Integer(), nullable=True),
        sa.Column('chosen_value', sa.String(length=500), nullable=True),
        sa.Column('officer_id', sa.String(length=100), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
        sa.ForeignKeyConstraint(['chosen_extracted_field_id'], ['extracted_fields.id'], ),
        sa.PrimaryKeyConstraint('resolution_id')
    )
    op.create_index(op.f('ix_field_resolutions_submission_id'), 'field_resolutions', ['submission_id'], unique=False)
    op.create_index(op.f('ix_field_resolutions_field_key'), 'field_resolutions', ['field_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_field_resolutions_field_key'), table_name='field_resolutions')
    op.drop_index(op.f('ix_field_resolutions_submission_id'), table_name='field_resolutions')
    op.drop_table('field_resolutions')
    # ### end Alembic commands ###
